using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    
    public float moveSpeed;
    private Rigidbody myRigidbody; // interacts with the Rigidbody movement system
    
    private Vector3 moveInput;
    private Vector3 moveVelocity;

    private Camera mainCamera;

    public bool useController;


    public bool canMove;
    
    // Start is called before the first frame update
    void Start()
    {
        print("Start Game");
        canMove = true;
        myRigidbody = GetComponent<Rigidbody>();
        mainCamera = FindObjectOfType<Camera>();
    }

    // Update is called once per frame (generated by PC)
    void Update()
    {

        if (canMove == false)
        {
            moveVelocity = Vector3.zero;
            return;
        }
        
        moveInput = new Vector3(Input.GetAxis("Horizontal"), 0f, Input.GetAxis("Vertical"));
        moveVelocity = moveInput * moveSpeed;

    //Point Character At Mouse Location
        if (!useController)
        {
            Ray cameraRay = mainCamera.ScreenPointToRay(Input.mousePosition);
            Plane groundPlane = new Plane(Vector3.up, Vector3.zero);
            float rayLength; //value for this will be how far the camera is from the ground

            if (groundPlane.Raycast(cameraRay, out rayLength)
            ) //sets however far the camera is from the ground based off of 
            {
                Vector3 pointToLook = cameraRay.GetPoint(rayLength);
                Debug.DrawLine(cameraRay.origin, pointToLook, Color.blue);

                transform.LookAt(new Vector3(pointToLook.x, transform.position.y, pointToLook.z));
            }
        }
        
    //Rotate with Right Stick Controller
        if (useController)
        { 
            Vector3 playerDirection = Vector3.right * Input.GetAxis("RHorizontal") +
                                      Vector3.forward * -Input.GetAxis("RVertical");

            if (playerDirection.sqrMagnitude > 0.0f)
            {
                transform.rotation = Quaternion.LookRotation(playerDirection, Vector3.up);
            }

            if (Input.GetAxis("RTrigger") > 0)
            {
                //Interaction stuff here
//                print("Right Trigger clicked up");    
            }

        }
        
    }
    
    
    // Update is always performed at the same time
    private void FixedUpdate()
    {
        myRigidbody.velocity = moveVelocity;
    }
}
