using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    
    public float moveSpeed;
    private Rigidbody myRigidbody; // interacts with the Rigidbody movement system
    
    private Vector3 moveInput;
    private Vector3 moveVelocity;
    
    // Start is called before the first frame update
    void Start()
    {
        myRigidbody = GetComponent<Rigidbody>();
    }

    // Update is called once per frame (generated by PC)
    void Update()
    {
        moveInput = new Vector3(Input.GetAxis("Horizontal"), 0f, Input.GetAxis("Vertical"));
        moveVelocity = moveInput * moveSpeed;
    }

    
    // Update is always performed at the same time
    private void FixedUpdate()
    {
        myRigidbody.velocity = moveVelocity;
    }
}
